JobOffer/job_offer/job_offer/urls.py
from django.contrib import admin
from django.urls import path, include
from job_offer_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name = "index"),
    path('', include('job_offer_app.urls', namespace = 'job_offer_app')),
]

JobOffer/job_offer/job_offer_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'job_offer_app'
urlpatterns = [
    path('job_offers/', views.JobOfferInfoListView.as_view(), name = "job_offer_list"),
    re_path(r'^job_offer/(?P<pk>\d+)/$', views.JobOfferInfoDetailView.as_view(), name = "job_offer_detail"),
    path('job_offer/create/', views.JobOfferInfoCreateView.as_view(), name = "job_offer_create"),
    re_path(r'^job_offer/update/(?P<pk>\d+)/$', views.JobOfferInfoUpdateView.as_view(), name = "job_offer_update"),
    re_path(r'^job_offer/delete/(?P<pk>\d+)/$', views.JobOfferInfoDeleteView.as_view(), name = "job_offer_delete"),
    path('users/', views.UserProfileInfoListView.as_view(), name = "users_list"),
    re_path(r'^users/(?P<pk>\d+)/$', views.UserProfileInfoDetailView.as_view(), name = "user_detail"),
    path('users/create/', views.UserProfileInfoCreateView.as_view(), name = "user_create"),
    re_path(r'^users/update/(?P<pk>\d+)/$', views.UserProfileInfoUpdateView.as_view(), name = "user_update"),
    re_path(r'^users/delete/(?P<pk>\d+)/$', views.UserProfileInfoDeleteView.as_view(), name = "user_delete")
]

JobOffer/job_offer/job_offer_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class UserProfileInfo(models.Model):
    firstname = models.CharField(max_length=256, blank=True, null=True)
    lastname = models.CharField(max_length = 256, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    password = models.CharField(max_length=256, blank=True, null=True)
    experience = models.FloatField(blank=False, null=False)
    resume = models.FileField(upload_to = 'resumes', blank=True)
    role = models.CharField(max_length = 256, blank=False, null=False)
    current_company = models.CharField(max_length=256)
    technology_stack = models.CharField(max_length=120)

    def __str__(self):
        return '%s %s' %(self.firstname, self.lastname)

    def get_absolute_url(self):
        return reverse("job_offer_app:user_detail", kwargs={"pk": self.pk})

class JobOfferInfo(models.Model):
    user_profile_info = models.ManyToManyField(UserProfileInfo, through='UserJobOffer',  related_name='users')
    company = models.CharField(max_length=20, blank=False, null=False)
    designation = models.CharField(max_length=20, blank=False, null=False)
    package = models.CharField(max_length=20)
    experience = models.CharField(max_length=30)
    technology_stack = models.CharField(max_length=50)

    def __str__(self):
        return '%s %s' % (self.company, self.designation)

    def get_absolute_url(self):
        return reverse("job_offer_app:job_offer_detail", kwargs={"pk": self.pk})

class UserJobOffer(models.Model):
    user_profile_info_id = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    job_offer_info_id = models.ForeignKey(JobOfferInfo, on_delete=models.CASCADE)

JobOffer/job_offer/user_profile_app/models.py
from django.db import models

# Create your models here.

JobOffer/job_offer/job_offer_app/forms.py
from django import forms
from .models import UserProfileInfo

class UserProfileInfoForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    
    class Meta():
        model = UserProfileInfo
        fields = '__all__'

JobOffer/job_offer/job_offer_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import UserProfileInfoForm

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['inject_me'] = 'I have injected here'
#         return context

class JobOfferInfoListView(ListView):
    context_object_name = 'job_offers' #default it will return lowercase model name underscore list i.e job_offer_info_list
    model = models.JobOfferInfo

class JobOfferInfoDetailView(DetailView):
    context_object_name = 'job_offer_info_detail' # default it will return lowercase model name i.e jobofferinfo
    model = models.JobOfferInfo
    template_name = 'job_offer_app/jobofferinfo_detail.html'

class JobOfferInfoCreateView(CreateView):
    fields = ('company', 'designation', 'package', 'experience', 'technology_stack')
    model = models.JobOfferInfo

class JobOfferInfoUpdateView(UpdateView):
    fields = ('designation', 'package', 'experience', 'technology_stack')
    model = models.JobOfferInfo

class JobOfferInfoDeleteView(DeleteView):
    model = models.JobOfferInfo
    success_url = reverse_lazy("job_offer_app:job_offer_list")

#Users CRUD

class UserProfileInfoListView(ListView):
    context_object_name = 'users' #default it will return lowercase model name underscore list i.e userprofileinfo_list
    model = models.UserProfileInfo

class UserProfileInfoDetailView(DetailView):
    context_object_name = 'user_detail' # default it will return lowercase model name i.e userprofileinfo
    model = models.UserProfileInfo
    template_name = 'job_offer_app/userprofileinfo_detail.html'

class UserProfileInfoCreateView(CreateView):
    form_class = UserProfileInfoForm
    template_name = 'job_offer_app/userprofileinfo_form.html'
    success_url = reverse_lazy('job_offer_app:users_list')

class UserProfileInfoUpdateView(UpdateView):
    fields = ('firstname', 'lastname', 'email', 'experience', 'role', 'current_company', 'technology_stack')
    template_name = 'job_offer_app/userprofileinfo_form.html'
    model = models.UserProfileInfo

class UserProfileInfoDeleteView(DeleteView):
    model = models.UserProfileInfo
    success_url = reverse_lazy("job_offer_app:users_list")

JobOffer/job_offer/user_profile_app/views.py
from django.shortcuts import render

# Create your views here.

JobOffer/job_offer/job_offer_app/templates/job_offer_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href={% url 'job_offer_app:job_offer_list' %}>JobOffers</a></li>
                <li><a class="navbar-link" href={% url 'job_offer_app:job_offer_create' %}>CreateJobOffer</a></li>
                <li><a class="navbar-link" href={% url 'admin:index' %}>Admin</a></li>
                <li><a class="navbar-link" href=""></a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        
        {% endblock body_block %}
    </div>
</body>
</html>

JobOffer/job_offer/job_offer_app/templates/job_offer_app/basic_app_user_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href={% url 'job_offer_app:users_list' %}>Users</a></li>
                <li><a class="navbar-link" href={% url 'job_offer_app:user_create' %}>CreateUser</a></li>
                <li><a class="navbar-link" href={% url 'admin:index' %}>Admin</a></li>
                <li><a class="navbar-link" href=""></a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        
        {% endblock body_block %}
    </div>
</body>
</html>

JobOffer/job_offer/job_offer_app/templates/job_offer_app/jobofferinfo_confirm_delete.html
{% extends "job_offer_app/basic_app_base.html" %}


{% block body_block %}
    <h1>Delete {{jobofferinfo.company}}  {{jobofferinfo.designation}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class = "btn btn-danger" value="Delete">
        <a href="{% url 'job_offer_app:job_offer_detail' pk=jobofferinfo.pk %}">Cancel</a>
    </form>
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/jobofferinfo_detail.html
{% extends "job_offer_app/basic_app_base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the Job Offer details page</h1>
        <h2>Job Offer Details</h2>
        <p>Company Name: {{job_offer_info_detail.company}}</p>
        <p>Designation: {{job_offer_info_detail.designation}}</p>
        <p>Package: {{job_offer_info_detail.package}} per annum</p>
        <p>Experience: {{job_offer_info_detail.experience}}</p>
        <p>Technology Stack: {{job_offer_info_detail.technology_stack}} per annum</p>
        <h3>Applicants for this job offer:</h3>

        {% for applicant in job_offer_info_detail.users.all %}
            <p>Name: {{applicant.name}}</p>
            <p>Role: {{applicant.role}}</p>
        {% endfor %}
    </div>    
    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'job_offer_app:update' pk=job_offer_info_detail.pk %}">Update</a></p>
        <p><a class="btn btn-danger" href="{% url 'job_offer_app:delete' pk=job_offer_info_detail.pk %}">Delete</a></p>
    </div>
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/jobofferinfo_form.html
{% extends "job_offer_app/basic_app_base.html" %}

{% block body_block %}
    <h1>
        
        {% if not form.instance.pk %}
            Create JobOfferInfo            
        {% else %}
            Update JobOfferInfo
        {% endif %}
            
    </h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/jobofferinfo_list.html
{% extends "job_offer_app/basic_app_base.html" %}

{% block body_block %}
    <h1>Welcome to a list of all the Job offers</h1>
    <ol>
         {% for job_offer in job_offers  %}
            <h2><li><a href="{{job_offer.id}}"><p>{{job_offer.company }}  {{ job_offer.designation}}</p></a></li></h2>
         {% endfor %}
    </ol>
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/userprofileinfo_confirm_delete.html
{% extends "job_offer_app/basic_app_user_base.html" %}


{% block body_block %}
    <h1>Delete {{userprofileinfo.firstname}} {{userprofileinfo.lastname}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class = "btn btn-danger" value="Delete">
        <a href="{% url 'job_offer_app:user_detail' pk=userprofileinfo.pk %}">Cancel</a>
    </form>
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/userprofileinfo_detail.html
{% extends "job_offer_app/basic_app_user_base.html" %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the User Profile Info page</h1>
        <h2>User Details</h2>
        <p>Username: {{user_detail.firstname}} {{user_detail.lastname}}</p>
        <p>Email: {{user_detail.email}}</p>
        <p>role: {{user_detail.role}}</p>
        <p>Experience: {{user_detail.experience}}</p>
        <p>Technology Stack: {{user_detail.technology_stack}} per annum</p>

    </div>    
    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'job_offer_app:user_update' pk=user_detail.pk %}">Update</a></p>
        <p><a class="btn btn-danger" href="{% url 'job_offer_app:user_delete' pk=user_detail.pk %}">Delete</a></p>
    </div>
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/userprofileinfo_form.html
{% extends "job_offer_app/basic_app_user_base.html" %}

{% block body_block %}
    <h1>
        
        {% if not form.instance.pk %}
            Create User
            Create UserProfileInfo
        {% else %}
            Update User
            Update UserProfileInfo
        {% endif %}
            
    </h1>

    <form method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  
{% endblock body_block %}

JobOffer/job_offer/job_offer_app/templates/job_offer_app/userprofileinfo_list.html
{% extends "job_offer_app/basic_app_user_base.html" %}

{% block body_block %}
    <h1>List of Users</h1>
    <ol>
         {% for user in users  %}
            <h2><li><a href="{{user.id}}"><p>{{user.firstname }} {{user.lastname}}</p></a></li></h2>
         {% endfor %}
    </ol>
{% endblock body_block %}

JobOffer/job_offer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href={% url 'job_offer_app:job_offer_list' %}>Job Offer</a></li>
                <li><a class="navbar-brand" href={% url 'job_offer_app:users_list' %}>Users</a></li>
                <li><a class="navbar-link" href={% url 'admin:index' %}>Admin</a></li>
                <li><a class="navbar-link" href=""></a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        
        {% endblock body_block %}
    </div>
</body>
</html>

JobOffer/job_offer/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home Page</h1>
  </div>
{% endblock body_block %}