DjangoLevelFour/learning_templates/basic_app/urls.py
from basic_app import views
from django.urls import path

app_name = 'basic_app'

urlpatterns = [
	path('', views.index, name= 'index'),
    path('other/', views.other, name = 'other'),
	path('relative/', views.relative_url_templates, name = 'relative'),
]

DjangoLevelFour/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index),
	path('basic_app/', include('basic_app.urls')),
	path('admin/', admin.site.urls),
]

DjangoLevelFour/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

DjangoLevelFour/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  context_dictionary = {'text':'hello_world', 'number': 100}
  return render(request, 'basic_app/index.html', context_dictionary)

def other(request):
  return render(request, 'basic_app/other.html')

def relative_url_templates(request):
  return render(request, 'basic_app/relative_url_templates.html')

DjangoLevelFour/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Page Title</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" media="screen" href="main.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="main.js"></script>
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a></li>
				<li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
				<li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
			</ul>
		</div>
	</nav>
	<div class="container">
		{% block body_block %}

		{% endblock body_block %}
	</div>
</body>
</html>

DjangoLevelFour/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}
		<h1>Welcome TO INDEX</h1>
		<h2>This is an example of template inheritance index.html.</h2>
		<h1>{{text|upper}}</h1>
		<h1>{{number|add:40}}</h1>
		<h1>{{text|cut:'_'}}</h1>
	{% endblock body_block %}

DjangoLevelFour/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}
		<h1>Welcome to Other Page</h1>
		<h2>This is an example of template inheritance.</h2>
	{% endblock body_block %}

DjangoLevelFour/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Relative URL</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" media="screen" href="main.css" />
	<script src="main.js"></script>
</head>
<body>
	<h1>Welcome to Relative URL Template Page.</h1>
	<a href="{% url 'basic_app:other' %}">The Other Page</a>
	<a href="{% url 'admin:index' %}">Admin Page</a>
	<a href="{% url 'basic_app:index' %}">Index Page</a>
</body>
</html>