AdvanceConcepts/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name = "index"),
    path('basic_app/', include('basic_app.urls', namespace = 'basic_app'))
]

AdvanceConcepts/advcbv/basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    path('school/', views.SchoolListView.as_view(), name = "school_list"),
    re_path(r'^school/(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name = "school_detail"),
    path('school/create/', views.SchoolCreateView.as_view(), name = "school_create"),
    re_path(r'^school/update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name = "school_update"),
    re_path(r'^school/delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name = "school_delete"),
    path('student/', views.StudentListView.as_view(), name = "student_list"),
    re_path(r'^student/(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name = "student_detail"),
    path('student/create/', views.StudentCreateView.as_view(), name = "student_create"),
    re_path(r'^student/update/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name = "student_update"),
    re_path(r'^student/delete/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name = "student_delete")
]

AdvanceConcepts/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
import datetime
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:school_detail", kwargs={"pk": self.pk})
    

class Student(models.Model):
    school = models.ForeignKey(School, related_name='students', on_delete= models.CASCADE)
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    date_of_joining = models.DateField(default = datetime.date.today())

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("basic_app:student_detail", kwargs={"pk": self.pk})

AdvanceConcepts/advcbv/basic_app/forms.py
from django import forms
from .models import Student, School


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'age', 'school')

class UpdateStudentForm(forms.ModelForm):
    
    class Meta:
        model = Student
        fields = ('name', 'age')

AdvanceConcepts/advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy
from .forms import CreateStudentForm, UpdateStudentForm
# Create your views here.
# def index(request):
#     return render(request, 'index.html')

class IndexView(TemplateView):
    template_name = 'index.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['inject_me'] = 'I have injected here'
#         return context

class SchoolListView(ListView):
    context_object_name = 'schools' #default it will return lowercase model name underscore list i.e school_list
    model = models.School
    template_name = 'basic_app/school_list.html'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail' # default it will return lowercase model name i.e school
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'location', 'principal')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:school_list")



class StudentListView(ListView):
    context_object_name = 'students' #default it will return lowercase model name underscore list i.e school_list
    model = models.Student
    template_name = 'basic_app/students_list.html'

class StudentDetailView(DetailView):
    context_object_name = 'student_detail' # default it will return lowercase model name i.e school
    model = models.Student
    template_name = 'basic_app/student_detail.html'

class StudentCreateView(CreateView):
    form_class = CreateStudentForm
    redirect_field_name = 'basic_app/student_detail.html'
    model = models.Student

class StudentUpdateView(UpdateView):
    form_class = UpdateStudentForm
    redirect_field_name = 'basic_app/student_detail.html'
    model = models.Student

class StudentDeleteView(DeleteView):
    model = models.Student
    success_url = reverse_lazy("basic_app:student_list")

AdvanceConcepts/advcbv/basic_app/templates/basic_app/_school_home.html
<h1>Welcome to School Home Page</h1>

AdvanceConcepts/advcbv/basic_app/templates/basic_app/_student_home.html
<h1>Welcome to Student Home Page</h1>

AdvanceConcepts/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href={% url 'basic_app:school_list' %}>Schools</a></li>
                <li><a class="navbar-brand" href={% url 'basic_app:school_create' %}>Create School</a></li>
                <li><a class="navbar-brand" href={% url 'basic_app:student_list' %}>Students</a></li>
                <li><a class="navbar-brand" href={% url 'basic_app:student_create' %}>Create Student</a></li> 
                <li><a class="navbar-link" href={% url 'index' %}>Home</a></li>
                <li><a class="navbar-link" href=""></a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        
        {% endblock body_block %}
    </div>
</body>
</html>

AdvanceConcepts/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}


{% block body_block %}
    <h1>Delete {{school.name}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class = "btn btn-danger" value="Delete">
        <a href="{% url 'basic_app:school_detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock body_block %}
    

AdvanceConcepts/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% load custom_tag %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the school details page</h1>
        <h2>School Details</h2>
        <p>Name: {{school_detail.name | lower}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Location: {{school_detail.location}}</p>
        <p>Number of students in the school: {{ school_detail | students_count }} </p>
        <h3>Students in this school:</h3>

        {% for student in school_detail.students.all %}
            <p>Name: {{student.name}}</p>
            <p>Age: {{student.age}}</p>
        {% endfor %}
    </div>    
    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'basic_app:school_update' pk=school_detail.pk %}">Update</a></p>
        <p><a class="btn btn-danger" href="{% url 'basic_app:school_delete' pk=school_detail.pk %}">Delete</a></p>
    </div>
{% endblock body_block %}
    

AdvanceConcepts/advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <h1>
        
        {% if not form.instance.pk %}
            Create School            
        {% else %}
            Update School
        {% endif %}
            
    </h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  
{% endblock body_block %}

AdvanceConcepts/advcbv/basic_app/templates/basic_app/school_list.html
{% include "basic_app/basic_app_base.html" %}
{% include "basic_app/_school_home.html" %}

{% block body_block %}
    <h2>List of all the schools</h2>
    <ol>
         {% for school in schools  %}
            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
         {% endfor %}
    </ol>
{% endblock body_block %}

AdvanceConcepts/advcbv/basic_app/templates/basic_app/student_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}


{% block body_block %}
    <h1>Delete {{student.name}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class = "btn btn-danger" value="Delete">
        <a href="{% url 'basic_app:student_detail' pk=student.pk %}">Cancel</a>
    </form>
{% endblock body_block %}
    

AdvanceConcepts/advcbv/basic_app/templates/basic_app/student_detail.html
{% extends "basic_app/basic_app_base.html" %}


{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the Student details page</h1>
        <h2>Student Details</h2>
        <p>Name: {{student_detail.name}}</p>
        <p>Age: {{student_detail.age}}</p>
        <p>Date of Joining: {{student_detail.date_of_joining |date:"d-m-Y" }}</p>
        <p>School Name: {{student_detail.school.name | default:"nothing"}}</p>
    </div>    
    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'basic_app:student_update' pk=student_detail.pk %}">Update</a></p>
        <p><a class="btn btn-danger" href="{% url 'basic_app:student_delete' pk=student_detail.pk %}">Delete</a></p>
    </div>
{% endblock body_block %}
    

AdvanceConcepts/advcbv/basic_app/templates/basic_app/student_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <h1>
        
        {% if not form.instance.pk %}
            Create Student            
        {% else %}
            Update Student
        {% endif %}
            
    </h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
  
{% endblock body_block %}

AdvanceConcepts/advcbv/basic_app/templates/basic_app/student_list.html
{% include "basic_app/basic_app_base.html" %}
{% include "basic_app/_student_home.html" %}

{% block body_block %}
    <h2>List of all the students</h2>
    <ol>
         {% for student in students  %}
            <h2><li><a href="{{student.id}}">{{student.name}}</a></li></h2>
         {% endfor %}
    </ol>
{% endblock body_block %}

AdvanceConcepts/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href={% url 'basic_app:school_list' %}>School</a></li>
                <li><a class="navbar-link" href={% url 'admin:index' %}>Admin</a></li>
                <li><a class="navbar-link" href=""></a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        
        {% endblock body_block %}
    </div>
</body>
</html>

AdvanceConcepts/advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home Page</h1>
  </div>
{% endblock body_block %}